### PR TITLE
separate hackage per package

### PR DESCRIPTION
**Pull request by brainrake**
- creates separate hackage per package so only changed dependencies are rebuilt
- easier to use
```
inherit (myHackages) extra-hackages extra-hackage-tarballs modules;
```
- is a monoid so extensible
- prefixes hackage names with `_` to hack priority

### CODE REVIEW

**Comment by brainrake** [comment]
```
> nix build
...
haskell-project-plan-to-nix-pkgs> Using index-state 2022-05-04T00:00:00Z
haskell-project-plan-to-nix-pkgs> Warning: The package list for '_mydep' is 19147 days old.
haskell-project-plan-to-nix-pkgs> Run 'cabal update' to get the latest list of available packages.
haskell-project-plan-to-nix-pkgs> Warning: Requested index-state 2022-05-04T00:00:00Z is newer than '_mydep'!
haskell-project-plan-to-nix-pkgs> Falling back to older state (2009-01-01T00:00:00Z).
haskell-project-plan-to-nix-pkgs> Warning: The package list for '_mydepdep' is 19147 days old.
haskell-project-plan-to-nix-pkgs> Run 'cabal update' to get the latest list of available packages.
haskell-project-plan-to-nix-pkgs> Warning: Requested index-state 2022-05-04T00:00:00Z is newer than '_mydepdep'!
haskell-project-plan-to-nix-pkgs> Falling back to older state (2009-01-01T00:00:00Z).
haskell-project-plan-to-nix-pkgs> Warning: The package list for 'hackage.haskell.org-at-2022-05-04T000000Z' is
haskell-project-plan-to-nix-pkgs> 19147 days old.
haskell-project-plan-to-nix-pkgs> Run 'cabal update' to get the latest list of available packages.
haskell-project-plan-to-nix-pkgs> Warning: Requested index-state 2022-05-04T00:00:00Z is newer than
haskell-project-plan-to-nix-pkgs> 'hackage.haskell.org-at-2022-05-04T000000Z'! Falling back to older state
haskell-project-plan-to-nix-pkgs> (2022-05-03T21:28:32Z).
haskell-project-plan-to-nix-pkgs> Resolving dependencies...
haskell-project-plan-to-nix-pkgs> Wrote freeze file: /build/tmp.wzA6tCpXcU/cabal.project.freeze
error: attribute 'mydep' missing

       at /nix/store/ryqxlzh82ikbyq9yq3z12b3hz52biwm5-haskell-project-plan-to-nix-pkgs/default.nix:13:31:

           12|         "filepath".revision = (((hackage."filepath")."1.4.2.1").revisions).default;
           13|         "mydep".revision = (((hackage."mydep")."0.0.1").revisions).default;
             |                               ^
           14|         "ghc-prim".revision = (((hackage."ghc-prim")."0.6.1").revisions).default;
       Did you mean one of mdp, medea, meep or model?
(use '--show-trace' to show detailed location information)
```

**Comment by brainrake** [comment]
Only changed dependencies are rebuilt. Here's how to test it:
- `nix build -L`
- change `mydep/MyDep.hs`, eg. add a newline
- `nix build -L`
- `mydepdep` should not be rebuilt

however, the whole process is pretty slow, building hackages takes a long time

**Review by L-as — APPROVED** [review]
We should merge this

**Comment by brainrake** [comment]
any results from testing?

**Comment by L-as** [comment]
I am using this in https://github.com/Plutonomicon/plutarch/pull/486 and it completely destroys evaluation time performance.
I think it's doing many IFDs sequentially potentially.

**Comment by brainrake** [comment]
both `mkHackageFor` and `mkHackagesFor` are available, so i'll merge this.

**Pull request merged**
